FROM nginx

WORKDIR /

RUN apt-get update && \
    apt-get install -y curl && \
    curl -sL https://deb.nodesource.com/setup_14.x | bash && \
    apt-get install -y nodejs && \
    npm install -g yarn

COPY ./package.json ./yarn.lock /
RUN yarn install

COPY ./nginx.conf.template /etc/nginx/templates/
RUN rm /etc/nginx/conf.d/default.conf

COPY ./src /src
COPY ./webpack.config.js /
RUN yarn build
