[package]
name = "slasyz_ru"
version = "0.1.0"
edition = "2018"

[dependencies]
chrono = "0.4"
colored = "2"
fern = "0.6"
lazy_static = "1.4"
log = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
warp = "0.3"
