version: '3.7'

services:
  gateway:
    build: gateway
    ports:
      - 8080:80
    depends_on:
      - backend
      - frontend

  frontend:
    build:
      context: ./frontend

  backend:
    build:
      context: ./backend
    depends_on:
      - database

  database:
    build: database
    volumes:
      - postgres_data:/volumes/postgresql/data/
    environment:
      - POSTGRES_USER=slasyz_ru
      - POSTGRES_PASSWORD=slasyz_ru
      - POSTGRES_DB=slasyz_ru

volumes:
  postgres_data:
