version: '3.9'

services:
  app:
    build: .
    command: ["/usr/local/bin/slasyz_ru"]
    ports:
      - "127.0.0.1:8001:8001/tcp"
    volumes:
      - cache_target:/target
      - cache_cargo:/root/target

volumes:  # TODO: wtf I wrote
  cache_target:
  cache_cargo:
