FROM python:3.9.1-slim-buster

EXPOSE 8000

WORKDIR /app

RUN apt-get update -y && apt-get install -y build-essential virtualenv firefox-esr gcc python3-dev libpq-dev

COPY ./requirements.txt ./Makefile /app/

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
RUN make init

COPY ./slasyz_ru /app/slasyz_ru
COPY ./templates /app/templates
COPY ./config-composer.json /app/config.json

ENTRYPOINT bash -c "make dev"
